server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    propreties:
      hibernate.format_sql: true

  elasticsearch:
    uris: http://localhost:9200